### ISSUE TITLE
[Feature Request] IBM Cloud Sendgrid Integration

### ISSUE THREAD

**Issue by movinglightspeed** [data-henrik/security-advisor-notifications#2]
Hi Henrik,

Since SendGrid is integrated already with IBM Cloud, could you also offer instructions for SendGrid as well? This way users do not have to sign up for mailjet (3rd party) but can utilize IBM Cloud interface to use SendGrid which is already integrated in billing etc.

This is most helpful for companies / organizations who do not have to go through the process of additional enterprise billing, accounts responsibilities through MailJet

https://cloud.ibm.com/catalog/infrastructure/email-delivery

Thank you,
Stanley
IBM Cloud Architect @ Deloitte

**Comment by data-henrik** [comment]
@movinglightspeed 
Hi Stanley,
I could add instructions when I have more time. Not within the next few weeks. The instructions and code are mainly to set up the mailing API, e.g., replace https://github.com/data-henrik/security-advisor-notifications/blob/master/src/mailjet.py#L11

I am open to PRs... ;-)

**Comment by data-henrik** [comment]
The APIs are similar: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html
Few lines would need to be replaced.

**Comment by data-henrik** [comment]
@movinglightspeed I have added SMTP support, so that most email services could be used.

**Comment by data-henrik** [comment]
https://sendgrid.com/docs/for-developers/sending-email/getting-started-smtp/
